version: 2.1

executors:
  node_container:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/typeorm-express-query-builder

jobs:

  setup:
    executor: node_container
    steps:
      - checkout
      - restore_cache:
          key: typeorm-express-query-builder-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: typeorm-express-query-builder-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths: "node_modules"
      - persist_to_workspace:
          root: ~/typeorm-express-query-builder
          paths:
            - .

  unit_tests:
    executor: node_container
    steps:
      - attach_workspace:
          at: ~/typeorm-express-query-builder
      - run: npm run test:cov
      - run: npm run codecov

  publish:
    executor: node_container
    steps:
      - attach_workspace:
          at: ~/typeorm-express-query-builder
      - run:
          name: Build package
          command: npm run build
      - run:
          name: Copy package.json
          coomand: cp ./package.json ./dist
      - run:
          name: Copy README.md
          coomand: cp ./README.md ./dist
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/typeorm-express-query-builder/dist/.npmrc
      - run:
          name: Change to dist dir & publish
          command: cd dist && npm publish

workflows:

  default:
    jobs:
      - setup
      - unit_tests:
          requires:
            - setup
      - publish:
          requires:
            - unit_tests
          filters:
            branches:
              only: master
